name: Check coverage

on:
  #  push:
  #    branches: [ main,test ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3

        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run coverage
        run: ./gradlew jacocoTestReport
      - name: JaCoCo Code Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.5
        with:
         paths: |
           ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml

